### ISSUE TITLE
Very Amazing Work!!

### ISSUE THREAD

**Issue by lijianxue77** [lapidshay/Diagnosis-of-software-networks-delays-and-failures#1]
Hi, thanks so much for this code.
But I have a question:
How to use Cytoscape to get 2000_nodes.png?
Any related codes, articles or links?
Thx

**Comment by lapidshay** [comment]
Hello!
The related code can be found in Main.ipynb:
- Cell 6 creates the graph.
- Cell 9 applies each node's latency as an attribute.
- Cell 10 exports the graph to a .gml file.

Cytoscape is used here only as a visualization tool:
I load the .gml file into Cytoscape, and manually sets the style configuration - namely, node size and color are mapped according to latency attribute value.
